name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: 'latest'
    - name: Activate venv
      run: | 
          make venv
          source .venv/bin/activate
          cp .env.local .env
    - name: Sync dependencies
      run: make dependencies
    - name: Run Lint
      run: make check
    - name: Run tests with code coverage
      run: make test
