name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: 'latest'
    - name: Install dependencies
      run: make install
    - name: Run Lint
      run: make check
    - name: Run tests with code coverage
      run: make test

